name: lab3_cicd

on:
  push:
    branches: [main]

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: "Install project dependencies"
        run: pip install -r requirements.txt

      - name: "Run tests and code coverage analysis"
        run: |
          mkdir -p test-results
          pytest --html=test-results/report.html --self-contained-html

      - name: "Archive pytest reports"
        uses: actions/upload-artifact@v4
        if: ${{!cancelled()}}
        with:
          name: "test results"
          path: test-results/
          if-no-files-found: error

  publish-package-as-artifact:
    needs: ["test-and-package"]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Create source archive
          run: |
            zip -r source_code.zip .
        - name: Upload source code artifact
          uses: actions/upload-artifact@v4
          with:
            name: source-code
            path: source_code.zip